### ISSUE TITLE
Show some Unity methods

### ISSUE THREAD

**Issue by ANF-Studios** [oliverbooth/X10D#40]
In the README file, it only shows methods from `X10D`'s namespace, not `X10D.Unity`, which is kind of a bummer as it does not fully show what X10D itself has to offer. I think it would be a good idea to also show some Unity extension methods.

**Comment by oliverbooth** [comment]
The README will be updated to link to better documentation closer to 3.0.0 release

**Comment by oliverbooth** [comment]
The X10D.Unity package is being temporarily retired due to X10D now being upgraded to .NET 6 as of 375a382e1b182d931517dc094ca889ca6ff2382e. Unity have stated that .NET 6 support is [planned on their roadmap](https://forum.unity.com/threads/unity-future-net-development-status.1092205/), but until such a time that Unity is updated - Unity support is being dropped.

**Comment by oliverbooth** [comment]
Unity support has been re-introduced as of 3.1.0, with X10D multi-targeting .NET 6 and .NET Standard 2.1 - meaning the package is usable from Unity 2021.2

Documentation still planned to be automated, but taking this off the back-burner now.

**Comment by oliverbooth** [comment]
Preliminary documentation created by DocFX is now live at https://oliverbooth.github.io/X10D/

These doc pages outline every single method available, though hand-written articles are still to be written. However, since the original issue is resolved, I'm closing!
