### ISSUE TITLE
[Request]: Check 2 FileSystemInfo point to the same path

### ISSUE THREAD

**Issue by RealityProgrammer** [oliverbooth/X10D#67]
### Type to extend

System.IO.FileSystemInfo

### Signature

```csharp
bool IsSamePath(FileSystemInfo other);
```

### Summary

```md
Check 2 system files point to the same path
```

### Parameters

| Parameter | Type    | Description                        |
| -         | -       | -                                  |
| other         | `FileSystemInfo` | File system to compare to. |

### Benefits

No string allocation because of span usage.
For some reason, .NET doesn't offer similar functionality, it only expose the FullName string at best. Yet people might use this in a non-efficient way (via string.TrimEnd, which allocate a new string).

### Drawbacks

Might have some special case that this will fail the check, but this is pretty much sufficient for normal file checking.

### Implementation Example

```csharp
return a.FullName.AsSpan().TrimEnd('\\').SequenceEqual(b.FullName.AsSpan().TrimEnd('\\'));
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by oliverbooth** [comment]
Interesting suggestion. Will add this soon

**Comment by oliverbooth** [comment]
> No string allocation because of span usage.

I'd like to point out that this wouldn't apply because the `FullName` property already returns a string. Calling `AsSpan` is pretty pointless and won't save an allocation if the property already allocates before-hand.

Fortunately, the property does not allocate and in fact returns a private string that's already allocated in the class. For this reason it's safe to just call `string.Equals`

**Comment by oliverbooth** [comment]
This also brings into question the need for such a method, when the caller could just call `string.Equals(value.FullName, other.FullName)`

**Comment by oliverbooth** [comment]
OP has redacted this request.
