### ISSUE TITLE
Add .NET 8 build target

### ISSUE THREAD

**Issue by oliverbooth** [oliverbooth/X10D#88]
.NET 8 releases 14 November 2023 at 16:00 UTC. This should now be added to the build pipeline.

**Comment by oliverbooth** [comment]
Paging @RealityProgrammer - bugfixes required in AVD optimisations.

**Comment by RealityProgrammer** [comment]
After discussion in the discord server, we've both agree to make AdvSimd/ARM Neon intrinsic implementations obsolete due to the lack of testing environment. For the time being, all the code will be commented out (not delete, so that we will have a solid foundation once we begin to support ARM Neon devices).
